name: kaya_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  country_picker: ^2.0.26
  flutter:
    sdk: flutter
  flutter_image_slideshow: ^0.1.6
  http: ^1.2.2
  intl: ^0.19.0
  provider: ^6.1.2
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
